CREATE TABLE IF NOT EXISTS ale_run (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    run_key VARCHAR(120) NOT NULL COMMENT '运行唯一键',
    domain VARCHAR(120) NOT NULL COMMENT '领域',
    discipline VARCHAR(120) NOT NULL COMMENT '学科',
    scenario VARCHAR(160) NOT NULL COMMENT '场景',
    difficulty VARCHAR(40) NOT NULL COMMENT '难度',
    input_mode VARCHAR(80) NOT NULL COMMENT '输入形态',
    output_mode VARCHAR(80) NOT NULL COMMENT '输出形态',
    verification_mode VARCHAR(80) NOT NULL COMMENT '验证方式',
    reference_strategy VARCHAR(80) NOT NULL COMMENT 'reference策略',
    target_count INT NOT NULL DEFAULT 1 COMMENT '目标task数量',
    codex_model VARCHAR(120) COMMENT 'Codex模型',
    status VARCHAR(40) NOT NULL COMMENT '状态',
    progress_percent INT NOT NULL DEFAULT 0 COMMENT '进度百分比',
    total_tasks INT NOT NULL DEFAULT 0 COMMENT '总task数',
    completed_tasks INT NOT NULL DEFAULT 0 COMMENT '完成task数',
    failed_tasks INT NOT NULL DEFAULT 0 COMMENT '失败task数',
    blocked_tasks INT NOT NULL DEFAULT 0 COMMENT '阻塞task数',
    output_root VARCHAR(1000) COMMENT '输出目录',
    log_path VARCHAR(1000) COMMENT 'Codex日志路径',
    summary_path VARCHAR(1000) COMMENT 'summary.json路径',
    error_message TEXT COMMENT '错误信息',
    started_at DATETIME COMMENT '开始时间',
    finished_at DATETIME COMMENT '结束时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ale_run_key (run_key),
    INDEX idx_ale_run_status (status),
    INDEX idx_ale_run_domain (domain)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ALE阶段一生成运行表';

CREATE TABLE IF NOT EXISTS ale_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    run_id BIGINT NOT NULL COMMENT '运行ID',
    task_id VARCHAR(200) NOT NULL COMMENT 'ALE task id',
    title VARCHAR(300) COMMENT '标题',
    domain VARCHAR(120) NOT NULL COMMENT '领域',
    discipline VARCHAR(120) COMMENT '学科',
    scenario VARCHAR(160) COMMENT '场景',
    difficulty VARCHAR(40) COMMENT '难度',
    status VARCHAR(40) NOT NULL COMMENT '状态',
    score DECIMAL(6,3) COMMENT 'oracle分数',
    task_dir VARCHAR(1000) COMMENT 'task目录',
    evidence_path VARCHAR(1000) COMMENT 'oracle证据路径',
    summary TEXT COMMENT '摘要',
    error_message TEXT COMMENT '错误信息',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ale_task_run_id (run_id),
    INDEX idx_ale_task_domain (domain),
    INDEX idx_ale_task_status (status),
    UNIQUE KEY uk_ale_task_run_task (run_id, task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ALE阶段一生成task表';
