CREATE TABLE IF NOT EXISTS swe_candidate (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    candidate_id VARCHAR(80) COMMENT '扫描内候选编号',
    repo VARCHAR(300) NOT NULL COMMENT 'GitHub repo, owner/name',
    pr_number INT COMMENT 'PR编号',
    pr_url VARCHAR(500) NOT NULL COMMENT 'PR URL',
    title VARCHAR(500) COMMENT 'PR标题',
    base_commit VARCHAR(100) COMMENT '基线commit',
    fix_commit VARCHAR(100) COMMENT '修复commit',
    merge_commit VARCHAR(100) COMMENT 'merge commit',
    primary_language VARCHAR(100) COMMENT '主语言',
    secondary_languages VARCHAR(500) COMMENT '辅助语言',
    patch_files INT COMMENT '变更文件数',
    source_files INT COMMENT '源码文件数',
    insertions INT COMMENT '新增行',
    deletions INT COMMENT '删除行',
    total_changed INT COMMENT '总变更行',
    gold_patch_files INT COMMENT 'gold文件数',
    gold_source_files INT COMMENT 'gold源码文件数',
    gold_insertions INT COMMENT 'gold新增行',
    gold_deletions INT COMMENT 'gold删除行',
    gold_total_changed INT COMMENT 'gold总变更行',
    test_patch_files INT COMMENT '测试文件数',
    test_insertions INT COMMENT '测试新增行',
    test_deletions INT COMMENT '测试删除行',
    test_total_changed INT COMMENT '测试总变更行',
    generated_or_i18n_ratio DOUBLE COMMENT '生成代码或i18n占比',
    score INT COMMENT '候选评分',
    candidate_grade VARCHAR(20) COMMENT '候选等级',
    grade_reason TEXT COMMENT '评级原因',
    candidate_status VARCHAR(40) COMMENT '候选状态',
    duplicate_status VARCHAR(40) DEFAULT 'NEW' COMMENT '去重状态',
    strengths TEXT COMMENT '优势信号JSON',
    risks TEXT COMMENT '风险信号JSON',
    sample_files TEXT COMMENT '样例文件JSON',
    raw_json JSON COMMENT '候选完整JSON',
    merged_at DATETIME COMMENT '合并时间',
    updated_at DATETIME COMMENT 'PR更新时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_swe_candidate_pr_url (pr_url),
    INDEX idx_swe_candidate_repo (repo),
    INDEX idx_swe_candidate_status (candidate_status),
    INDEX idx_swe_candidate_duplicate (duplicate_status),
    INDEX idx_swe_candidate_score (score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SWE-Pro候选PR登记表';
